# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  # If using public/private key pair
  #public_key: "%env(resolve:JWT_PUBLIC_KEY_PATH)%"
  # Other configurations...
  token_ttl: 3600
